NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/{version}/doc

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

utility:
    type: rest
    prefix: /api/{version}
    resource: AppBundle\Controller\UtilityController
    


